version: '3'
services:
  tc-mm-processor:
    image: mm-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    network_mode: "host"
    volumes:
      - "../:/mm-processor"
    working_dir: /mm-processor
